name: pocket_chips
description: Pocket poker chips for your phone. Play poker with only cards.

publish_to: 'none' 

version: 1.0.5+11

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  
  flutter:
    sdk: flutter
    
  # FOR OPEN URL and email and google play review
  url_launcher: ^6.0.20
  flutter_mailer: ^3.0.1
  #in_app_review: ^2.0.6
  
  # Monitization
  #unity_ads_plugin: ^0.3.7
  #purchases_flutter: ^5.7.0
  # my_target_flutter: ^0.1.0+3
  # in_app_purchase: ^3.0.8
  

  # UI
  page_transition: "^2.0.5"
  material_design_icons_flutter: any
  cupertino_icons: ^1.0.2
  numberpicker: ^2.1.1
  fluttertoast: ^9.0.0
  google_fonts: ^6.1.0
  onboarding: ^3.1.0
  flutter_screenutil: ^5.8.3
  
  # Iternal
  path_provider: ^2.0.11
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  #easy_localization: ^3.0.0
  shared_preferences: ^2.0.0 
  #easy_localization_loader: ^1.0.1+1
  package_info_plus: ^9.0.0     
  #flutter_yandex_games: ^0.0.6

  
  #window_size:
  #  git:
  #    url: https://github.com/google/flutter-desktop-embedding
  #    path: plugins/window_size
  # lint: ^2.0.1
  #reorderables: ^0.4.3
  #advanced_icon: ^0.1.2
  #flutter_keyboard_visibility: ^5.2.0
  #pulsing_button: ^0.0.6
  #carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^6.0.0
  


flutter:
  generate: true
  uses-material-design: true

  assets:
      - assets/translations/
      - assets/сard_back.jpg
      - assets/сard_back_dark.jpg
      - assets/card_front.png
      - assets/card_front_dark.png
      - assets/table_dark.png
      - assets/table_light.png
      - assets/init_logo.png
      - assets/pattern.png
      - assets/chips/
      - assets/social/
      - assets/faces/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:

     - family: Ubuntu
       fonts:
         - asset: fonts/Ubuntu-Bold.ttf
           weight: 700
         - asset: fonts/Ubuntu-Medium.ttf
           weight: 500
         - asset: fonts/Ubuntu-Regular.ttf
           weight: 400
         - asset: fonts/Ubuntu-Light.ttf
           weight: 300